### ISSUE TITLE
API implementation checklist

### ISSUE THREAD

**Issue by DeckerSU** [KomodoPlatform/rosetta-komodo#1]
![image](https://github.com/DeckerSU/rosetta-komodo/assets/22120003/0bf6e4c3-b587-4d01-98c1-b62f9dfe745e)

**[Data](https://docs.cloud.coinbase.com/rosetta/docs/data-api-overview) API**

- [x] `/network/list`
- [x] `/network/options`
- [x] `/network/status`
- [x] `/block`
- [x] `/block/transaction`
- [x] `/account/balance`
- [x] `/account/coins`
- [x] `/mempool`
- [x] `/mempool/transaction` ❌ (not implemented in `mesh-bitcoin`)
- [x] `/call` ❌ (not implemented in `mesh-bitcoin`)

**[Construction](https://docs.cloud.coinbase.com/rosetta/docs/construction-api-overview) API**

- [x] `/construction/derive`
- [x] `/construction/preprocess`
- [x] `/construction/metadata`
- [x] `/construction/payloads` (still need to check txes with multiple inputs for correct digest)
- [x] `/construction/parse` (at present only unsigned parse is implemented)
- [x]  `/construction/combine`
- [x] `/construction/hash`
- [x] `/construction/submit`
